[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[namenode]
master1 ansible_host=192.168.56.10

[datanodes]
datanode1 ansible_host=192.168.56.12
datanode2 ansible_host=192.168.56.13

[resourcemanager]
master1 ansible_host=192.168.56.10

[nodemanagers]
datanode1 ansible_host=192.168.56.12
datanode2 ansible_host=192.168.56.13

[hadoop_cluster:children]
namenode
datanodes
